version: "3"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=myuser
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3033:3033"
    env_file:
     - ./.env
